In [3]:
#The plotly Python library is an interactive, open-source plotting library that supports over 40 unique chart 

#Importing pandas library to read the dataset
# and manipulate data by cleaning it or changing datatype
import pandas as pd

#The figures produced by Plotly Express can always be built from the ground up 
#using graph objects, but this approach typically takes 5-100 lines of code rather than 1.
import plotly.express as px
import plotly.graph_objs as go

#Its a combination of date and time along with the attributes year, month, day, hour, minute, second, microsecond
#Python Datetime module supplies classes to work with date and time. These classes provide a number of functions to deal with dates, times and time intervals.
from datetime import *
from plotly.subplots import make_subplots


#TO find longitude and latitude using neighbourhood
from geopy.geocoders import Nominatim

from plotly.offline import init_notebook_mode, iplot
init_notebook_mode(connected=True)

#!pip install geopy
#!pip install --upgrade plotly

In [4]:
# Reading dataset
path = 'C:/Users/Admin/OneDrive - University of Ottawa/uOttawa/Winter2022/ML/A1/New folder/Predicting-Medical-Appointment-Status/'
df=pd.read_excel('MedicalCentre.xlsx')
df.sample(5)

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show
79316,9.729256e+13,5671002,F,2016-05-06T15:13:23Z,2016-05-13T00:00:00Z,48,SANTOS DUMONT,0,0,0,0,0,0,No
54983,3.933479e+13,5677063,F,2016-05-09T17:44:44Z,2016-05-09T00:00:00Z,47,DA PENHA,0,0,0,0,0,0,No
72708,3.552656e+12,5719602,F,2016-05-19T11:40:52Z,2016-05-25T00:00:00Z,37,JABOUR,0,0,0,0,0,1,No
25409,2.187992e+11,5728311,M,2016-05-20T15:56:37Z,2016-05-25T00:00:00Z,48,SANTA TEREZA,0,0,0,0,0,1,Yes
56008,3.668727e+12,5677049,M,2016-05-09T17:35:06Z,2016-05-09T00:00:00Z,7,REDENÃ‡ÃƒO,0,0,0,1,0,0,No

In [5]:
# Renaming columns to names that make more sense
#df.rename(columns={'Handcap': 'Handicap','No-show': 'Missed'}, inplace=True)
# replacing wrong values in handcap column since it only contains 0 or 1 it can't have the [2] as a value
df.Handcap.replace(2,1 ,inplace=True)
df['Handcap'].replace(3,1,inplace=True)
df['Handcap'].replace(4,1,inplace=True)
# removing values in age column with -1
df=df[(df.Age > -1)]
# changing the data type of ScheduledDay and AppintmentDay to datetime
df['ScheduledDay'] = pd.to_datetime(df['ScheduledDay'])
df['AppointmentDay']= pd.to_datetime(df['AppointmentDay'])
# no duplicate values
sum(df.duplicated())
# printing the first 5 values in the dataset
df.head()

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show
0,2.987250e+13,5642903,F,2016-04-29 18:38:08+00:00,2016-04-29 00:00:00+00:00,62,JARDIM DA PENHA,0,1,0,0,0,0,No
1,5.589978e+14,5642503,M,2016-04-29 16:08:27+00:00,2016-04-29 00:00:00+00:00,56,JARDIM DA PENHA,0,0,0,0,0,0,No
2,4.262962e+12,5642549,F,2016-04-29 16:19:04+00:00,2016-04-29 00:00:00+00:00,62,MATA DA PRAIA,0,0,0,0,0,0,No
3,8.679512e+11,5642828,F,2016-04-29 17:29:31+00:00,2016-04-29 00:00:00+00:00,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No
4,8.841186e+12,5642494,F,2016-04-29 16:07:23+00:00,2016-04-29 00:00:00+00:00,56,JARDIM DA PENHA,0,1,1,0,0,0,No

**Deriving needed data for visualization**

1) Remove all rows with age less than 0 because it doesn't make sense.

2) Change the datatypes of Scheduled day and Appointment Day to their correct datatypes(datetime) to extract from them days of the week.

3) Check for duplicate rows.

4) Calculate the time between the Scheduled day and Appointment day and use it as a new feature.

In [6]:
# Deriving Day column from AppointmentDay column
df['Day']=df['AppointmentDay'].dt.day_name()
# Deriving Number of diseases by adding [Alcoholism,Handicap,Diabetes,Hipertension]
df['Num_Of_Dieases']=df['Alcoholism']+df['Handcap']+df['Diabetes']+df['Hipertension']
# Derving Age groups [Young Frin 0 to 20 years][Adult from 20 to 60 years][Elderly from 60 to the maximum  age in the dataset]
df['age-group']=pd.cut(df['Age'],[-1,20,60,df.Age.max()+1],labels=['Young','Adult','Elderly'])
# Deriving time_left column by subtracting AppointmentDay from ScheduledDay
df['time_left']=df['AppointmentDay']-df['ScheduledDay']

a=timedelta(days = 0)
b=timedelta(days = 7)
c=timedelta(days = 30)
zero=timedelta(days = 0)
# time_left can't have negative values
df=df[df['time_left']>zero]
# Derving Time into 3 categories [Short from 0 to 7 days][Intermediate from 7 to 30 days][Long from 30 to maximum number of days in the dataset]
df['Time']=pd.cut(df['time_left'],[a,b,c,df.time_left.max()],labels=['Short','Intermediate','Long'])

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 71959 entries, 5 to 110526
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientId       71959 non-null  float64
 1   AppointmentID   71959 non-null  int64
 2   Gender          71959 non-null  object
 3   ScheduledDay    71959 non-null  datetime64[ns, UTC]
 4   AppointmentDay  71959 non-null  datetime64[ns, UTC]
 5   Age             71959 non-null  int64
 6   Neighbourhood   71959 non-null  object
 7   Scholarship     71959 non-null  int64
 8   Hipertension    71959 non-null  int64
 9   Diabetes        71959 non-null  int64
 10  Alcoholism      71959 non-null  int64
 11  Handcap         71959 non-null  int64
 12  SMS_received    71959 non-null  int64
 13  No-show         71959 non-null  object
 14  Day             71959 non-null  object
 15  Num_Of_Dieases  71959 non-null  int64
 16  age-group       71959 non-null  category
 17  time_left       71959 non-null  timedelta64[ns]
 18  Time            71959 non-null  category
dtypes: category(2), datetime64[ns, UTC](2), float64(1), int64(9), object(4), timedelta64[ns](1)
memory usage: 10.0+ MB

There are no missing values

In [16]:
# Extracting Address from neighbourhood and find longitude and latitude

#declaring locations dictionary
locations = dict()
#for uniquie values of neighbourhood
for neighbor in df["Neighbourhood"].unique():
    #Send http request to get location Logitude, Latitude and address  
    geolocator = Nominatim(user_agent="agent_name")
    #find location using Neighbourhood unique  values and country name "Brazil"
    location = geolocator.geocode(neighbor+" "+"brasile")
    # print(location)
    #Assign unique neighbourhoods to the key of the locations dictionary and location to the value
    locations[neighbor] = location

In [17]:
#declaring empty lists
address = []
longitude = []
latitude = []
#for every neighbourhood in df
for neighbor in df["Neighbourhood"]:
    #if the value of  the locations dic is empty assign nan to it (Nan values Would be dropped later)  
    if locations[neighbor] is None:
        longitude.append(None)
        address.append(None)
        latitude.append(None)
    continue
    #add values to the lists

    longitude.append(locations[neighbor].longitude)
    latitude.append(locations[neighbor].latitude)
    address.append(locations[neighbor].address)

In [21]:
longitude

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 ...]